name: Devcontainer Build

on:
  pull_request:
    branches:
      - main
    paths:
      - '.devcontainer/devcontainer.json'

jobs:
  validate:
    name: Validate Dev Container Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install Dev Container CLI
        run: npm install -g @devcontainers/cli
      
      - name: Validate and build Dev Container
        run: devcontainer build --workspace-folder .
